eureka:
  client:
    register-with-eureka: false

server:
  port: 8080
spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      discover:
        locator:
          enabled: true
      routes:
        - id: car
          uri: http://localhost:8090
          predicates:
            - Path=/api/car/**
        - id: agency
          uri: http://localhost:9090
          predicates:
            - Path=/api/agency/**